services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=ineedmasterdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
  app:
    image: alexdockercompose/ineedmaster:latest
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ineedmasterdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_ADMIN=admin